global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
      
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
      
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
      
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka_exporter:9308']
      
  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']
      
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']